### ISSUE TITLE
Could not find module `@ember/modifier` imported from `ember-focus-trap/modifiers/focus-trap`

### ISSUE THREAD

**Issue by seemajune** [josemarluedke/ember-focus-trap#10] opened 2019-05-24 19:36 UTC
I'm testing basic usage in an ember-cli app, v3.9.0

`<div {{focus-trap}}><button>test</button></div>`

and receive this error. Any assistance would be much appreciated. 😅

**Comment by josemarluedke** [comment] 2019-05-25 04:08
Hello. 

Thanks for reporting this error.

I have tried to reproduce it by creating a new Ember app using version 3.9.0, but I was not able to get this error. 

Could you try to create a reproduction?

You could also try to check the following:

- Your `ember-cli-babel` version. Make sure you are on recent versions.
- Check if adding `ember-modifier-manager-polyfill` to your project dependencies solves this issue.

**Comment by seemajune** [comment] 2019-05-25 18:01
Thank you for replying so quickly! Here are my versions:
- ember-cli-babel@7.7.3
- ember-cli@3.9.0
- ember-modifier-manager-polyfill@1.0.3

steps to reproduce:
1. `ember install ember-focus-trap` and then `yarn`
2. `ember install `ember-modifier-manager-polyfill ` and then `yarn`
3. rebuilt app
4. added the below to one of my component templates, just to test basic usage:
```
<div {{focus-trap}}>
  <button>test</button>
</div>
```
5. Receive these errors:
<img width="1025" alt="Screen Shot 2019-05-25 at 2 00 57 PM" src="https://user-images.githubusercontent.com/2113081/58373058-972e6c00-7ef5-11e9-86fe-ac3502662636.png">

**Comment by josemarluedke** [comment] 2019-09-03 20:07
Will close this as I was unable to reproduce. Feel free to reopen if you still having this issue.

**Closed as completed by josemarluedke** 2019-09-03 20:07 UTC
